version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli yq
      - yum install -y jq
      - pip install aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - STACK_NAME=$(yq -r '.default.deploy.parameters.stack_name' parameters/samconfig.yaml)
      - echo "Stack name from config ${STACK_NAME}"

  build:
    commands:
      - echo Executing changeset
      - aws cloudformation execute-change-set \
        --stack-name ${STACK_NAME} \
        --change-set-name `aws cloudformation list-change-sets --stack-name ${STACK_NAME} --query 'Summaries[0].ChangeSetName' --output text`

  post_build:
    commands:
      - echo Changeset executed
