version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - echo Starting pre-build phase...

  build:
    commands:
      - echo Build started on `date`
      - sam build --template-file templates/root-template.yaml
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket cicd-sam-test-artifacts-bucket --output-template-file packaged-template.yaml

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - packaged-template.yaml
    - templates/**/*
    - parameters/**/*
    - pipeline/**/*
  discard-paths: no
