version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - echo Starting pre-build phase...

  build:
    commands:
      - echo Creating changeset
      - |
        sam deploy \
          --template-file packaged-template.yaml \
          --config-file parameters/samconfig.yaml \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --no-execute-changeset

  post_build:
    commands:
      - echo Changeset created
