version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - sam --version

  build:
    commands:
      - echo Build started on `date`
      - sam build
      - sam package --template-file templates/root-template.yaml --s3-bucket cicd-sam-test-artifacts-bucket --output-template-file packaged-template.yaml

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - packaged-template.yaml
    - templates/**/*
    - parameters/**/*
  discard-paths: no
