version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli yq
      - yum install -y jq
      - pip install aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - STACK_NAME=$(yq -r '.default.deploy.parameters.stack_name' parameters/samconfig.yaml)
      - echo "Stack name from config ${STACK_NAME}"

  build:
    commands:
      - echo Creating changeset
      - |
        sam deploy \
          --template-file packaged-template.yaml \
          --config-file parameters/samconfig.yaml \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --no-execute-changeset

  post_build:
    commands:
      - echo Changeset created
