version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - echo Starting pre-deploy phase...
      - ls -lR /codebuild/output/src*/src/s3/00/ #SourceArtifact
      - ls -lR /codebuild/output/src*/src/s3/01/ #BuildArtifact

  build:
    commands:
      - echo deploy started on `date`
      - sam deploy --template-file /codebuild/output/src*/src/s3/01/packaged-template.yaml --config-file=/codebuild/output/src*/src/s3/00/parameters/samconfig.yaml

  post_build:
    commands:
      - echo Deploy completed on `date`
