version: 0.1

default:
  deploy:
    parameters:
      stack_name: samsnssqsstack
      resolve_s3: true
      confirm_changeset: true
      capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_AUTO_EXPAND
      parameter_overrides:
        - SNSTopicName=SampleSNSTopic2
        - SQSQueueName=SampleSQSQueue2
        - LambdaName=SampleMessageProcessorFunction2
        - DLQName=SampleDeadLetterQueue2
        - VisibilityTimeout=60
        - MessageRetentionPeriod=3600
        - MaxReceiveCount=2
